### PR TITLE
functional tests tests protractor to codecept migration

### PR DESCRIPTION
**Pull request by sreekanthpuligadda**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8742 

### Change description ###

Functional tests, protrator to codecept migration

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by udaydenduluri33 — APPROVED** [review]
@sreekanthpuligadda  I can see Codecept changes and package.json changes. Also, the build is green.
LGTM. Thanks

**Comment by udaydenduluri33** [comment]
@sreekanthpuligadda  can you please attach the JIRA ID or EPIC ID please? Thanks

**Review by Daniel-Lam — APPROVED** [review]
@sreekanthpuligadda - very big PR, but approved

**Review by udaydenduluri33 — APPROVED** [review]

**Review by Daniel-Lam — APPROVED** [review]
@sreekanthpuligadda - re-approved

**Pull request merged**
